source("read_data.R")
powerData <- readData()
png("plot3.png",width=480,height=480,units="px")
plot(powerData$Date, powerData$Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering")
lines(powerData$Date, powerData$Sub_metering_1)
lines(powerData$Date, powerData$Sub_metering_2, col="red")
lines(powerData$Date, powerData$Sub_metering_3, col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"), lwd=c(1,1,1))
dev.off()