source("read_data.R")
powerData <- readData()
png("plot1.png",width=480,height=480,units="px")
hist(powerData$Global_active_power, xlab="Global Active Power (kilowatts)", col="red", main="Global Active Power")
dev.off()